version: "3.9"  # optional since v1.27.0
services:
  postgresdb:
    image: postgres
    container_name: postgres
    restart: always 
    ports: 
      - 5432:5432
    volumes: 
      - data:/var/lib/postgresql/data
  server: 
    build: .
    depends_on: 
      - postgresdb
    ports: 
      - '3000:3000'
    volumes: 
      - ./src:/src
    container_name: airsoft
    
volumes:
  data:
