version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: postgres
    restart: always
    env_file: 
      - .env
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
  server:
    build: 
      context: .
    container_name: airsoft
    environment: 
      POSTGRES_HOST: postgresdb
    ports: 
      - '3000:3000'
    depends_on: 
      - postgresdb
    restart: always
    command: npm run dev
